const DESKTOP_BREAKPOINT: number = 1024

const MAX_EXPENSE_FORM_VALUE: number = 100000

const MAX_EXPENSE_FORM_DECIMAL: number = String(MAX_EXPENSE_FORM_VALUE).length

export { DESKTOP_BREAKPOINT, MAX_EXPENSE_FORM_VALUE, MAX_EXPENSE_FORM_DECIMAL }
